### ISSUE TITLE
회원 가입 기능 추가

### ISSUE THREAD

**Issue by manyoung** [sunyi233/Coinmodu#18]
회원 가입 기능 추가 개발 필요
현재 지메일 로긴 편리하기는 하나 회원들의 개인 정보 유출에 대한 우려(지메일 비번 유출)로 회원 가입 유도가 안될 수 있음.

**Comment by sunyi233** [comment]
계정 시스템은 하나로 제한하는 것이 보안의 측면에서 이롭고 사용자도 적응이 되면 하나의 계정 시스템에서 든든함을 느낄 것입니다.

한편, 지적하신 웹에서 암호 입력시 불안할 것 같다는 느낌에 대한 불안함은 향후 앱이 만들어지면 해소됩니다.
